#!/usr/bin/env python3
"""Build wave-specific GSS pole files from the canonical poles.

For every GSS wave in the public model release, reads the model's own answer
labels (streaming only the archive's source maps; nothing is installed),
resolves the canonical poles with ``polar_vectors.resolve_poles`` and writes:

  assets/polar_vectors/gss/gss_YYYY_polar_vectors.csv   (variable,R,L)
  assets/polar_vectors/gss/pole_resolution_report.csv    every item x wave decision
  assets/polar_vectors/gss/README.md                     per-wave summary

Usage:
  python scripts/build_gss_polar_vectors.py            # all 35 GSS waves
  python scripts/build_gss_polar_vectors.py --waves 2018 2024
"""
from __future__ import annotations

import argparse
import csv
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import fetch_models  # noqa: E402
import pipeline as core  # noqa: E402
from build_model_coverage import read_source_maps  # noqa: E402
from polar_vectors import CANONICAL, CORRECTIONS, WAVE_DIR, load_corrections, resolve_poles, write_pole_csv  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--waves", nargs="*", help="e.g. 2018 2024 (default: all GSS waves)")
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()

    manifest = fetch_models.load_manifest()
    keys = sorted(k for k in manifest["models"] if k.startswith("gss/"))
    if args.waves:
        keys = [k for k in keys if k.split("_")[-1] in set(args.waves)]

    def support(key):
        url = manifest["base_url"].rstrip("/") + "/" + manifest["models"][key]["archive"]
        return key, read_source_maps(url)

    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as ex:
        supports = dict(ex.map(support, keys))

    left, right = core.load_polar_vectors_csv(str(CANONICAL))
    corrections = load_corrections(CORRECTIONS)
    report_rows = []
    summary = []
    for key in keys:
        year = key.split("_")[-1]
        L, R, rep = resolve_poles(left, right, supports[key], corrections)
        write_pole_csv(WAVE_DIR / f"gss_{year}_polar_vectors.csv", L, R)
        for r in rep:
            report_rows.append({"wave": year, **r})
        items_kept = sorted({r["item"] for r in rep if r["status"] != "dropped"})
        n = lambda s: sum(1 for r in rep if r["status"] == s)  # noqa: E731
        summary.append((year, len(items_kept), len(L), n("corrected") + n("renamed"),
                        sum(1 for r in rep if r["status"] == "dropped" and r["reason"] == "item not in wave"),
                        sum(1 for r in rep if r["status"] == "dropped" and r["reason"] != "item not in wave")))
        print(f"GSS {year}: {len(items_kept)}/{len(left)} items, {len(L)} pole variables, "
              f"{summary[-1][3]} corrected/renamed, {summary[-1][4]} not in wave, {summary[-1][5]} unresolved")

    WAVE_DIR.mkdir(parents=True, exist_ok=True)
    with open(WAVE_DIR / "pole_resolution_report.csv", "w", newline="", encoding="utf-8") as fh:
        cols = ["wave", "item", "variable", "status", "reason", "L_original", "L_used", "R_original", "R_used"]
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(report_rows)

    lines = [
        "# Wave-specific GSS ideology poles",
        "",
        "Generated by `scripts/build_gss_polar_vectors.py` from the canonical poles",
        "(`../polar_vectors.csv`) and the documented corrections (`../gss_pole_corrections.csv`),",
        "checked against each wave's native model labels. DTAG uses `gss_YYYY_polar_vectors.csv`",
        "automatically for the GSS YYYY model. An item is kept only if both its L and R answers",
        "exist in that wave; every decision is in `pole_resolution_report.csv`.",
        "",
        f"Canonical items: {len(left)}",
        "",
        "| Wave | Items kept | Pole variables | Corrected / renamed | Not asked in wave | Unresolved (dropped) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    lines += [f"| {y} | {a} | {b} | {c} | {d} | {e} |" for y, a, b, c, d, e in summary]
    unresolved = [r for r in report_rows if r["status"] == "dropped" and r["reason"] != "item not in wave"]
    if unresolved:
        lines += ["", "## Unresolved answers (dropped from both poles)", ""]
        lines += [f"- GSS {r['wave']} `{r['variable'] or r['item']}`: {r['reason']}" for r in unresolved]
    (WAVE_DIR / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(keys)} wave files + report to {WAVE_DIR}")


if __name__ == "__main__":
    main()
